### ISSUE TITLE
Enable mounting directories from host to task container on runtime

### ISSUE THREAD

**Issue by pedrovgp** [spaszek/airflow_project#6]
My use case is this: I have a directory (/dir/my-data) in my computer, which contains input_csv_files and to which a task should save the output_csv_files.

I have added it to docker-compose, under the worker service:
volumes:
      - /dir/my-data:/dir/my-data

Now, I want to bind it to the task container when it runs.

**Comment by spaszek** [comment]
Seems like you fixed it yourself. Thanks!
